#!/usr/bin/env python3
"""Regenerate the collapsible table of contents in README.md and docs/*.md.

    uv run python scripts/update_toc.py            # rewrite every page in place
    uv run python scripts/update_toc.py --check    # exit 1 if any is out of date

A page opts in by containing a '## Contents' heading; pages without one are left
alone, so a short page never grows a pointless index.

The TOC is emitted as pure HTML rather than Markdown-in-HTML. GitHub only
parses Markdown inside an HTML block after a blank line, and a blank line also
*ends* the HTML block, so mixing the two makes list nesting unpredictable.
With no blank lines the whole TOC is one uninterrupted HTML block, which
renders identically everywhere and survives GitHub's sanitizer.

Top-level sections that have subsections become <details>; the rest stay plain
links, so nothing expands to reveal an empty list.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

START = "## Contents"
END = "---"
GENERATED_NOTE = (
    "<!-- Generated by scripts/update_toc.py — run it after adding a heading. -->"
)

# github-slugger: lowercase, drop everything that is not a letter, number,
# space, hyphen or underscore, then spaces -> hyphens. Backticks, em dashes and
# punctuation vanish; the spaces around them do not.
_STRIP = re.compile(r"[^\w\- ]", re.UNICODE)


def _slug(text: str, seen: dict[str, int]) -> str:
    s = _STRIP.sub("", text.strip().lower()).replace(" ", "-")
    n = seen.get(s, 0)
    seen[s] = n + 1
    return s if n == 0 else f"{s}-{n}"


def _esc(text: str) -> str:
    """Escape for HTML text, dropping the Markdown code markers HTML cannot use."""
    return (
        text.replace("`", "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _headings(lines: list[str]) -> list[tuple[int, str]]:
    """Return (level, text) for every heading, ignoring fenced code blocks.

    The fence check is what keeps a '## Executive takeaway' inside a template
    sample out of the TOC.

    Every level is returned, not just the ones the TOC shows, because GitHub
    numbers duplicate slugs across all headings on the page: with an `# Setup`
    above a `## Setup`, the second is `setup-1`. Slugging only h2/h3 would emit
    `setup` and link to the wrong place.
    """
    found, in_fence = [], False
    for line in lines:
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = re.match(r"^(#{1,6}) (.+?)\s*$", line)
        if m:
            found.append((len(m.group(1)), m.group(2)))
    return found


def build_toc(lines: list[str]) -> list[str]:
    seen: dict[str, int] = {}
    sections: list[tuple[str, str, list[tuple[str, str]]]] = []
    for level, text in _headings(lines):
        # Slug every heading, so the dedup counter matches GitHub's, but show
        # only h2/h3 — an h1 is the page title and h4+ is too fine for an index.
        anchor = _slug(text, seen)
        if level == 2:
            # The Contents heading indexes everything else, not itself.
            if text.strip().lower() == "contents":
                continue
            sections.append((text, anchor, []))
        elif level == 3 and sections:
            sections[-1][2].append((text, anchor))

    out = [GENERATED_NOTE, "<ul>"]
    for text, anchor, children in sections:
        link = f'<a href="#{anchor}">{_esc(text)}</a>'
        if not children:
            out.append(f"  <li>{link}</li>")
            continue
        # `open` so subsections are visible on load and findable by Ctrl-F;
        # collapsed content is invisible to in-page search until expanded.
        out += [
            "  <li>",
            "    <details open>",
            f"      <summary>{link}</summary>",
            "      <ul>",
        ]
        out += [
            f'        <li><a href="#{a}">{_esc(t)}</a></li>' for t, a in children
        ]
        out += ["      </ul>", "    </details>", "  </li>"]
    out.append("</ul>")
    return out


def _span(path: Path, lines: list[str]) -> tuple[int, int]:
    """Return the line indices bounding the current TOC body.

    The block ends at whichever comes first: a horizontal rule, or the next
    section heading. Accepting both means a page can set the TOC off with a
    rule (as README does) or just let the next section end it, without every
    page needing the same furniture.
    """
    start = next(i for i, line in enumerate(lines) if line.strip() == START)
    try:
        end = next(
            i
            for i in range(start + 1, len(lines))
            if lines[i].strip() == END or lines[i].startswith("## ")
        )
    except StopIteration:
        raise SystemExit(
            f"{path}: nothing closes the '{START}' block — add a '{END}' rule "
            "or a following '## ' heading"
        )
    return start, end


def pages() -> list[Path]:
    """Every page that opted in by having a Contents heading."""
    candidates = [REPO_ROOT / "README.md", *sorted((REPO_ROOT / "docs").glob("*.md"))]
    return [
        p
        for p in candidates
        if p.is_file()
        and any(
            line.strip() == START for line in p.read_text(encoding="utf-8").splitlines()
        )
    ]


def rebuild(path: Path) -> tuple[list[str], list[str]]:
    """Return (current lines, what the file should contain)."""
    lines = path.read_text(encoding="utf-8").splitlines()
    start, end = _span(path, lines)
    return lines, lines[: start + 1] + [""] + build_toc(lines) + [""] + lines[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any TOC does not match its headings",
    )
    args = parser.parse_args()

    stale: list[Path] = []
    for path in pages():
        lines, rebuilt = rebuild(path)
        if lines == rebuilt:
            continue
        stale.append(path)
        if not args.check:
            path.write_text("\n".join(rebuilt) + "\n", encoding="utf-8")

    rel = [str(p.relative_to(REPO_ROOT)) for p in stale]
    if not stale:
        print(f"All {len(pages())} tables of contents are up to date.")
        return 0
    if args.check:
        print(
            f"Out of date: {', '.join(rel)}\n"
            "Run: uv run python scripts/update_toc.py",
            file=sys.stderr,
        )
        return 1
    print(f"Rewrote {len(stale)} table(s) of contents: {', '.join(rel)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
