#!/usr/bin/env python3
"""Regenerate README.md's collapsible table of contents.

    uv run python scripts/update_toc.py            # rewrite README.md in place
    uv run python scripts/update_toc.py --check    # exit 1 if it is out of date

The TOC is emitted as pure HTML rather than Markdown-in-HTML. GitHub only
parses Markdown inside an HTML block after a blank line, and a blank line also
*ends* the HTML block, so mixing the two makes list nesting unpredictable.
With no blank lines the whole TOC is one uninterrupted HTML block, which
renders identically everywhere and survives GitHub's sanitizer.

Top-level sections that have subsections become <details>; the rest stay plain
links, so nothing expands to reveal an empty list.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

README = Path(__file__).resolve().parent.parent / "README.md"

START = "## Contents"
END = "---"
GENERATED_NOTE = (
    "<!-- Generated by scripts/update_toc.py — run it after adding a heading. -->"
)

# github-slugger: lowercase, drop everything that is not a letter, number,
# space, hyphen or underscore, then spaces -> hyphens. Backticks, em dashes and
# punctuation vanish; the spaces around them do not.
_STRIP = re.compile(r"[^\w\- ]", re.UNICODE)


def _slug(text: str, seen: dict[str, int]) -> str:
    s = _STRIP.sub("", text.strip().lower()).replace(" ", "-")
    n = seen.get(s, 0)
    seen[s] = n + 1
    return s if n == 0 else f"{s}-{n}"


def _esc(text: str) -> str:
    """Escape for HTML text, dropping the Markdown code markers HTML cannot use."""
    return (
        text.replace("`", "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _headings(lines: list[str]) -> list[tuple[int, str]]:
    """Return (level, text) for every real heading, ignoring fenced code blocks.

    The fence check is what keeps a '## Executive takeaway' inside a template
    sample out of the TOC.
    """
    found, in_fence = [], False
    for line in lines:
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = re.match(r"^(#{2,3}) (.+?)\s*$", line)
        if m:
            found.append((len(m.group(1)), m.group(2)))
    return found


def build_toc(lines: list[str]) -> list[str]:
    seen: dict[str, int] = {}
    sections: list[tuple[str, str, list[tuple[str, str]]]] = []
    for level, text in _headings(lines):
        anchor = _slug(text, seen)
        if level == 2:
            # The Contents heading indexes everything else, not itself.
            if text.strip().lower() == "contents":
                continue
            sections.append((text, anchor, []))
        elif sections:
            sections[-1][2].append((text, anchor))

    out = [GENERATED_NOTE, "<ul>"]
    for text, anchor, children in sections:
        link = f'<a href="#{anchor}">{_esc(text)}</a>'
        if not children:
            out.append(f"  <li>{link}</li>")
            continue
        out += ["  <li>", "    <details>", f"      <summary>{link}</summary>", "      <ul>"]
        out += [
            f'        <li><a href="#{a}">{_esc(t)}</a></li>' for t, a in children
        ]
        out += ["      </ul>", "    </details>", "  </li>"]
    out.append("</ul>")
    return out


def _span(lines: list[str]) -> tuple[int, int]:
    """Return the line indices bounding the current TOC body."""
    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == START)
    except StopIteration:
        raise SystemExit(f"{README}: no '{START}' heading to anchor the TOC to")
    try:
        end = next(
            i for i in range(start + 1, len(lines)) if lines[i].strip() == END
        )
    except StopIteration:
        raise SystemExit(f"{README}: '{START}' is not closed by a '{END}' rule")
    return start, end


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the TOC does not match the headings",
    )
    args = parser.parse_args()

    lines = README.read_text(encoding="utf-8").splitlines()
    start, end = _span(lines)
    rebuilt = lines[: start + 1] + [""] + build_toc(lines) + [""] + lines[end:]

    if rebuilt == lines:
        print("TOC is up to date.")
        return 0
    if args.check:
        print(
            "TOC is out of date. Run: uv run python scripts/update_toc.py",
            file=sys.stderr,
        )
        return 1
    README.write_text("\n".join(rebuilt) + "\n", encoding="utf-8")
    print(f"Rewrote the TOC in {README.name}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
